### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by ialmetwally** [adjust/android_sdk#181]
The following crash happens a lot more than (4000 times) using SDK version 4.1.0

It occurs on different android versions: 4.4.2, 4.2.2, 5.0.2, 5.1

Stack Trace:

```java
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'long com.adjust.sdk.ActivityState.lastActivity' on a null object reference
       at com.adjust.sdk.ActivityHandler.updateActivityState(ActivityHandler.java:713)
       at com.adjust.sdk.ActivityHandler.endInternal(ActivityHandler.java:527)
       at com.adjust.sdk.ActivityHandler.access$400(ActivityHandler.java:34)
       at com.adjust.sdk.ActivityHandler$SessionHandler.handleMessage(ActivityHandler.java:368)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by nonelse** [comment]
This is was possible case, if onPause was called before the sdk was properly initialized.
Since [v4.1.1](https://github.com/adjust/android_sdk/releases/tag/v4.1.1), it has been fixed to prevent this.

**Comment by ialmetwally** [comment]
Thanks I'll update the SDK!

**Comment by uerceg** [comment]
@ialmetwally Just to double check some situations regarding this issue, would it be possible for you to send me your ProGuard settings file? If it's not something you want to share publicly in here, you can send us an email to support@adjust.com and reference this issue.

Thanks in advance.

Cheers

**Comment by ialmetwally** [comment]
@uerceg The issue was fixed when I updated the SDK version

**Comment by uerceg** [comment]
@ialmetwally Thanks for the update. 👍
