### ISSUE TITLE
Adjust seems like not handling bad network situation well

### ISSUE THREAD

**Issue by Paulus6** [adjust/android_sdk#190]
Hi All,
       we have integrated Adjust to our app, but when network is not good, there is some log showing Adjust not handing the situation well:

05-23 09:40:17.590 7734-7793/xxxxx E/Adjust: Failed to track session. (Request failed: java.io.IOException: Hostname 'app.adjust.com' was not verified) Will retry later

05-23 09:40:23.734 7734-7746/xxxxxx E/StrictMode: **A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.**
                                                                java.lang.Throwable: Explicit termination method 'close' not called
                                                                    at dalvik.system.CloseGuard.open(CloseGuard.java:184)
                                                                    at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:271)
                                                                    at com.android.okhttp.Connection.upgradeToTls(Connection.java:197)
                                                                    at com.android.okhttp.Connection.connect(Connection.java:151)
                                                                    at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276)
                                                                    at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
                                                                    at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:373)
                                                                    at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:106)
                                                                    at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:208)
                                                                    at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
                                                                    at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:25)
                                                                    at com.adjust.sdk.Util.createPOSTHttpsURLConnection(Util.java:315)
                                                                    at com.adjust.sdk.RequestHandler.sendInternal(RequestHandler.java:61)
                                                                    at com.adjust.sdk.RequestHandler.access$000(RequestHandler.java:27)
                                                                    at com.adjust.sdk.RequestHandler$1.run(RequestHandler.java:52)
                                                                    at android.os.Handler.handleCallback(Handler.java:739)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                    at android.os.Looper.loop(Looper.java:135)
                                                                    at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by uerceg** [comment]
Hi @Paulus6 

And sorry for the delayed answer. Can you please specify a bit more what do you mean when you say "network is not good"?

**Comment by uerceg** [comment]
Hi @Paulus6 

Are you still facing this error with latest SDK version (4.10.2)?

**Comment by Obaied** [comment]
Closed due to inactivity.
