### ISSUE TITLE
Out of memory error on SharedPreferencesManager.saveRawReferrerArray and getRawReferrerArray

### ISSUE THREAD

**Issue by maarcooliveira** [adjust/android_sdk#315]
We are using the sdk on version 4.12.0, and our crashlytics started reporting the two crashes below:

```
Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:325)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)
Caused by java.lang.OutOfMemoryError: Failed to allocate a 5885096 byte allocation with 4312008 free bytes and 4MB until OOM
       at java.lang.StringBuilder.toString(StringBuilder.java:408)
       at org.json.JSONStringer.toString(JSONStringer.java:430)
       at org.json.JSONArray.toString(JSONArray.java:586)
       at com.adjust.sdk.SharedPreferencesManager.saveRawReferrerArray(SourceFile:98)
       at com.adjust.sdk.SharedPreferencesManager.saveRawReferrer(SourceFile:87)
       at com.adjust.sdk.AdjustInstance$7.run(SourceFile:448)
       at com.adjust.sdk.Util$1.doInBackground(SourceFile:96)
       at com.adjust.sdk.Util$1.doInBackground(SourceFile:92)
       at android.os.AsyncTask$2.call(AsyncTask.java:305)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)
```

and

```
Caused by java.lang.OutOfMemoryError: Failed to allocate a 126484 byte allocation with 8388608 free bytes and 9MB until OOM; failed due to fragmentation (required continguous free 126976 bytes where largest contiguous free 12288 bytes)
       at java.util.Arrays.copyOf(Arrays.java:3231)
       at java.util.Arrays.copyOf(Arrays.java:3204)
       at java.util.ArrayList.grow(ArrayList.java:249)
       at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:223)
       at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:215)
       at java.util.ArrayList.add(ArrayList.java:441)
       at org.json.JSONArray.put(JSONArray.java:185)
       at org.json.JSONTokener.readArray(JSONTokener.java:429)
       at org.json.JSONTokener.nextValue(JSONTokener.java:103)
       at org.json.JSONArray.(JSONArray.java:92)
       at org.json.JSONArray.(JSONArray.java:108)
       at com.adjust.sdk.SharedPreferencesManager.getRawReferrerArray(SourceFile:167)
       at com.adjust.sdk.SharedPreferencesManager.getRawReferrerIndex(SourceFile:208)
       at com.adjust.sdk.SharedPreferencesManager.getRawReferrer(SourceFile:147)
       at com.adjust.sdk.SharedPreferencesManager.saveRawReferrer(SourceFile:76)
       at com.adjust.sdk.AdjustInstance$7.run(SourceFile:448)
       at com.adjust.sdk.Util$1.doInBackground(SourceFile:96)
       at com.adjust.sdk.Util$1.doInBackground(SourceFile:92)
       at android.os.AsyncTask$2.call(AsyncTask.java:305)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)
```
Any idea on what could be causing that? 
It happened about 230 times on the last two weeks, and we were not able to reproduce it so far.

**Comment by uerceg** [comment]
Hi @maarcooliveira 

We haven't had any similar reports like this so far. We are investigating and will keep you posted in here.

**Comment by uerceg** [comment]
@maarcooliveira 

Any regularity in OS versions / manufacturer on devices from which you have seen the crashes?

**Comment by maarcooliveira** [comment]
@uerceg 
No, most of devices are from Samsung, Motorola and LG, but it matches our user base. As for OS, it happens on all android versions, from 4.4.4 to 7.1.1.

**Comment by maarcooliveira** [comment]
Hi @uerceg 
Do you have any updates on this issue?

**Comment by uerceg** [comment]
Hi @maarcooliveira 

Sorry for delay in ping, actually we have released Android SDK v4.12.2 (https://github.com/adjust/android_sdk/releases/tag/v4.12.2) couple of days ago that should hopefully address this issue. Would be great if you can give it a try and let us know if you are still facing this issue with newest SDK version.

Looking forward to hear from you.

Cheers

**Comment by uerceg** [comment]
@maarcooliveira 

Today we have released v4.12.3 (https://github.com/adjust/android_sdk/releases/tag/v4.12.3) where we improved the logic even more to address hopefully all potential occurrences of issue like this. Feel free to give it a try and let us know if you noticed any improvements.

Cheers

**Comment by maarcooliveira** [comment]
Hi @uerceg 

We added the newest version in our next release, that is planned to go live next week. I'll let you know once we have the results. Thank you!

**Comment by uerceg** [comment]
Great! Looking forward to hear from you guys. Cheers.

**Comment by maarcooliveira** [comment]
Hi @uerceg 
Sorry for the delay. We are no longer seeing this problem with the 4.12.3 sdk. 
Thank you for the support!

**Comment by uerceg** [comment]
Great. Thanks for the update. Cheers! :beer:
