### ISSUE TITLE
CustomScheduledExecutor.java line 60 com.adjust.sdk.CustomScheduledExecutor.submit

### ISSUE THREAD

**Issue by HyakYegoryaln** [adjust/android_sdk#325]
Fatal Exception: java.lang.OutOfMemoryError: pthread_create (stack size 16384 bytes) failed: Try again
       at java.lang.VMThread.create(VMThread.java)
       at java.lang.Thread.start(Thread.java:1029)
       at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:920)
       at java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1553)
       at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:306)
       at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:503)
       at java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:602)
       at com.adjust.sdk.CustomScheduledExecutor.submit(CustomScheduledExecutor.java:60)
       at com.adjust.sdk.ActivityHandler.onPause(ActivityHandler.java:295)
       at com.adjust.sdk.AdjustInstance.onPause(AdjustInstance.java:94)
       at com.adjust.sdk.Adjust.onPause(Adjust.java:51)
       at com.example.App$AdjustLifecycleCallbacks.onActivityPaused(App.java:231)
       at android.app.Application.dispatchActivityPaused(Application.java:237)
       at android.app.Activity.onPause(Activity.java:1379)
       at android.support.v4.app.FragmentActivity.onPause(FragmentActivity.java:441)
       at com.example.screen.main.MainActivity.onPause(MainActivity.java:211)
       at android.app.Activity.performPause(Activity.java:5645)
       at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1239)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3383)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3352)
       at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3330)
       at android.app.ActivityThread.access$1100(ActivityThread.java:172)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1325)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5653)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by uerceg** [comment]
@HyakYegoryaln 

Which SDK version are you using?

**Comment by HyakYegoryaln** [comment]
implementation 'com.adjust.sdk:adjust-android:4.12.1'
implementation 'com.android.installreferrer:installreferrer:1.0'

**Comment by nonelse** [comment]
On which conditions did this happen? We already tried to replicate the issue but had no luck.
Was it on an emulator or a real device? Which emulator/device with which os version was it on?
Was it under heavy load from other things besides the adjust sdk? 
Can you reproduce it with predictable steps? Could we reproduce it with an example app?

**Comment by HyakYegoryaln** [comment]
Crash from Crashlytics, can not reproduce
Devices: LG G2,  Galaxy S5
OS versins :  5.0.2    4.4.2

using:
implementation 'com.adjust.sdk:adjust-android:4.12.1'
implementation 'com.android.installreferrer:installreferrer:1.0'

**Comment by davidchai** [comment]
Here is a similar crash log from a cocos2dx mobile game
Device: Sharp AQUOS R SHV39 (HUR), 
OS: Android 8.0
SDK Version: 4.13
`
java.lang.OutOfMemoryError: 
at java.lang.Thread.nativeCreate (Native Method)
at java.lang.Thread.start (Thread.java:733)
at java.util.concurrent.ThreadPoolExecutor.addWorker (ThreadPoolExecutor.java:970)
at java.util.concurrent.ThreadPoolExecutor.ensurePrestart (ThreadPoolExecutor.java:1611)
at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute (ScheduledThreadPoolExecutor.java:342)
at java.util.concurrent.ScheduledThreadPoolExecutor.schedule (ScheduledThreadPoolExecutor.java:562)
at com.adjust.sdk.CustomScheduledExecutor.schedule (CustomScheduledExecutor.java:64)
at java.util.concurrent.ScheduledThreadPoolExecutor.submit (ScheduledThreadPoolExecutor.java:664)
at com.adjust.sdk.CustomScheduledExecutor.submit (CustomScheduledExecutor.java:54)
at com.adjust.sdk.ActivityHandler.onPause (ActivityHandler.java:313)
at com.adjust.sdk.AdjustInstance.onPause (AdjustInstance.java:110)
at com.adjust.sdk.Adjust.onPause (Adjust.java:74)
at com.xs.a.a.a.a.onMainActivityPause (Statistic3rdImpl.java:171)
at org.cocos2dx.lua.HwSdkMgr.onMainActivityPause (HwSdkMgr.java:80)
at org.cocos2dx.lua.AppActivity.onPause (AppActivity.java:218)
at android.app.Activity.performPause (Activity.java:7156)
at android.app.Instrumentation.callActivityOnPause (Instrumentation.java:1408)
at android.app.ActivityThread.performPauseActivityIfNeeded (ActivityThread.java:4044)
at android.app.ActivityThread.performPauseActivity (ActivityThread.java:4021)
at android.app.ActivityThread.performPauseActivity (ActivityThread.java:3995)
at android.app.ActivityThread.handlePauseActivity (ActivityThread.java:3969)
at android.app.ActivityThread.-wrap15 (Unknown Source)
at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1651)
at android.os.Handler.dispatchMessage (Handler.java:105)
at android.os.Looper.loop (Looper.java:164)
at android.app.ActivityThread.main (ActivityThread.java:6627)
at java.lang.reflect.Method.invoke (Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:240)
at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:767)
`

**Comment by CharlieXK** [comment]
Here is also one similar crash log from android native SDK
OS version: Android 7.0
SDK version: SDK 4.13
Device: samsung-SM-J330G

Description：Could not allocate JNI Env

java.lang.Thread.nativeCreate(Native
Method)
java.lang.Thread.start(Thread.java:731)
java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:941)
java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1582)
java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:313)
java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
com.adjust.sdk.CustomScheduledExecutor.schedule(CustomScheduledExecutor.java:64)
java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:635)
com.adjust.sdk.CustomScheduledExecutor.submit(CustomScheduledExecutor.java:54)
com.adjust.sdk.ActivityHandler.onResume(ActivityHandler.java:293)
com.adjust.sdk.AdjustInstance.onResume(AdjustInstance.java:100)
com.adjust.sdk.Adjust.onResume(Adjust.java:66)
com.pesoloan.adjust.AppLifecycleCallbacks.onActivityResumed(AppLifecycleCallbacks.java:26)
android.app.Application.dispatchActivityResumed(Application.java:240)
android.app.Activity.onResume(Activity.java:1335)
android.support.v4.app.FragmentActivity.onResume(FragmentActivity.java:485)
com.trello.rxlifecycle.components.support.RxAppCompatActivity.onResume(RxAppCompatActivity.java:59)
com.pesoloan.base.BaseActivity.onResume(BaseActivity.java:88)
com.pesoloan.view.MainActivity.onResume(MainActivity.java:433)
android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1277)
android.app.Activity.performResume(Activity.java:7115)
android.app.ActivityThread.performResumeActivity(ActivityThread.java:3821)
android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3885)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1692)
android.os.Handler.dispatchMessage(Handler.java:102)
android.os.Looper.loop(Looper.java:154)
android.app.ActivityThread.main(ActivityThread.java:6776)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)

**Comment by uerceg** [comment]
Hey guys, thanks for sharing all these details, we're working on this one, but it would really help if any one of you can maybe share steps how to reproduce the crash, in case you are able to? So far we're unable to reproduce it which makes it a bit hard to catch and determine is there a path which can always provoke it.

**Comment by CharlieXK** [comment]
I checked with client. They are also trying to reproduce. They said it's usually like: enter a certain sub page, then return to home page and then crashes. But not 100% happens. So they also haven't reproduce it.
