### ISSUE TITLE
NonSdkApiUsedViolation in getVmInstructionSet function

### ISSUE THREAD

**Issue by C0lumbo** [adjust/android_sdk#347]
Running an Android P preview with the detectNonSdkApiUsage strict mode enabled outputs warnings about Adjust's getVmInstructionSet/getVMRuntimeObject functions.

The calls to getRuntime and vmInstructionSet are considered non SDK calls. I believe that they will trigger exceptions in future releases of Android P unless they are removed/replaced (https://developer.android.com/preview/restrictions-non-sdk-interfaces).

Log output:

07-26 11:39:54.102 10360-10408/com.mycompany.mygame D/StrictMode: StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Ldalvik/system/VMRuntime;->getRuntime()Ldalvik/system/VMRuntime;
        at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
        at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
        at java.lang.Class.getDeclaredMethodInternal(Native Method)
        at java.lang.Class.getPublicMethodRecursive(Class.java:2075)
        at java.lang.Class.getMethod(Class.java:2063)
        at java.lang.Class.getMethod(Class.java:1690)
        at com.adjust.sdk.Reflection.invokeMethod(Reflection.java:246)
        at com.adjust.sdk.Reflection.invokeStaticMethod(Reflection.java:233)
        at com.adjust.sdk.Reflection.getVMRuntimeObject(Reflection.java:24)
        at com.adjust.sdk.Reflection.getVmInstructionSet(Reflection.java:32)
        at com.adjust.sdk.Util.getVmInstructionSet(Util.java:533)
        at com.adjust.sdk.DeviceInfo.getVmInstructionSet(DeviceInfo.java:312)
        at com.adjust.sdk.DeviceInfo.<init>(DeviceInfo.java:95)
        at com.adjust.sdk.ActivityHandler.initI(ActivityHandler.java:666)
        at com.adjust.sdk.ActivityHandler.access$000(ActivityHandler.java:32)
        at com.adjust.sdk.ActivityHandler$1.run(ActivityHandler.java:207)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.adjust.sdk.CustomScheduledExecutor$RunnableWrapper.run(CustomScheduledExecutor.java:95)
        at java.lang.Thread.run(Thread.java:764)
07-26 11:39:54.124 10360-10408/com.mycompany.mygame D/StrictMode: StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Ldalvik/system/VMRuntime;->vmInstructionSet()Ljava/lang/String;
        at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
        at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
        at java.lang.Class.getDeclaredMethodInternal(Native Method)
        at java.lang.Class.getPublicMethodRecursive(Class.java:2075)
        at java.lang.Class.getMethod(Class.java:2063)
        at java.lang.Class.getMethod(Class.java:1690)
        at com.adjust.sdk.Reflection.invokeMethod(Reflection.java:246)
        at com.adjust.sdk.Reflection.invokeInstanceMethod(Reflection.java:240)
        at com.adjust.sdk.Reflection.getVmInstructionSet(Reflection.java:34)
        at com.adjust.sdk.Util.getVmInstructionSet(Util.java:533)
        at com.adjust.sdk.DeviceInfo.getVmInstructionSet(DeviceInfo.java:312)
        at com.adjust.sdk.DeviceInfo.<init>(DeviceInfo.java:95)
        at com.adjust.sdk.ActivityHandler.initI(ActivityHandler.java:666)
        at com.adjust.sdk.ActivityHandler.access$000(ActivityHandler.java:32)
        at com.adjust.sdk.ActivityHandler$1.run(ActivityHandler.java:207)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.adjust.sdk.CustomScheduledExecutor$RunnableWrapper.run(CustomScheduledExecutor.java:95)
        at java.lang.Thread.run(Thread.java:764)

**Comment by uerceg** [comment]
Hi @C0lumbo 

Thanks for the report. We are aware of this thing and also in communication with Google to see if this currently light grey bucket item will make to their official API list or not. We'll act accordingly once decision is made and remove it from SDK in case it doesn't become part of official API.

We'll keep you posted. In case you have any other questions, feel free to ping us in here.

Cheers

**Comment by C0lumbo** [comment]
Android Pie got released today - any update from google about these light grey non-SDK calls?

**Comment by uerceg** [comment]
Hi @C0lumbo 

Still no update on this one and even if Google decides to move it to public API it will take a while. Until that discussion is done, we'll release an update of the SDK in which we'll remove access to this field and warnings should not be present anymore.

Will keep you posted in here.

**Comment by C0lumbo** [comment]
Looks like that change made it into 4.15.0, so I think this issue can be closed.

**Comment by uerceg** [comment]
Oh yeah, sorry @C0lumbo, we forgot to ping you in here. You're right, v4.15.0 should have addressed this issue and good to hear that you saw it did. Thanks for the ping. Cheers.
