### ISSUE TITLE
Pre-installed trackers with adjust-dtt tools issue

### ISSUE THREAD

**Issue by Den-Rimus** [adjust/android_sdk#370]
Hi!

I'm having troubles using this `adjust-dtt` tool for adding a single default tracker into our apk that is to be provided for pre-install marketing campaign.

I started with release signed apk and did all the steps from [this tutorial](https://github.com/adjust/android_sdk/blob/master/doc/english/pre_install_tracker_tool.md) - all went well except that app was crashing at startup.

My thought was that this is due to proguard, but trying it with proguard disabled or with non-release (`minifyEnabled = false`) apk ended up with the same crash:

I get `java.lang.IllegalArgumentException: Unable to create converter for class <my_api_response_class>` when executing API call using retrofit2 which down below in stacktrace is caused by
```java
Caused by: java.lang.IllegalStateException: No BuiltInsLoader implementation was found. Please ensure that the META-INF/services/ is not stripped from your application and that the Java virtual machine is not running under a security manager
        at kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoader$Companion$Instance$2.invoke(BuiltInsLoader.kt:39)
        at kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoader$Companion$Instance$2.invoke(BuiltInsLoader.kt:36)
        at kotlin.SafePublicationLazyImpl.getValue(LazyJVM.kt:107)
        at kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoader$Companion.getInstance(Unknown Source:7)
        at kotlin.reflect.jvm.internal.impl.builtins.KotlinBuiltIns.createBuiltInsModule(KotlinBuiltIns.java:127)
        at kotlin.reflect.jvm.internal.impl.builtins.jvm.JvmBuiltIns.<init>(JvmBuiltIns.kt:43)
        at kotlin.reflect.jvm.internal.impl.builtins.jvm.JvmBuiltIns.<init>(JvmBuiltIns.kt:18)
        at kotlin.reflect.jvm.internal.components.RuntimeModuleData$Companion.create(RuntimeModuleData.kt:58)
        at kotlin.reflect.jvm.internal.ModuleByClassLoaderKt.getOrCreateModule(moduleByClassLoader.kt:58)
        at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data$moduleData$2.invoke(KDeclarationContainerImpl.kt:37)
        at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data$moduleData$2.invoke(KDeclarationContainerImpl.kt:34)
        at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92)
        at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31)
        at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data.getModuleData(Unknown Source:7)
        at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:47)
        at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:44)
2019-02-12 10:58:13.571 com.rewedigital.shop.debug E/AndroidRuntime:     at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92)
        at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31)
        at kotlin.reflect.jvm.internal.KClassImpl$Data.getDescriptor(Unknown Source:7)
        at kotlin.reflect.jvm.internal.KClassImpl.getDescriptor(KClassImpl.kt:179)
        at kotlin.reflect.jvm.internal.KClassImpl.isAbstract(KClassImpl.kt:268)
        at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:184)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:130)
        at retrofit2.converter.moshi.MoshiConverterFactory.responseBodyConverter(MoshiConverterFactory.java:91)
        at retrofit2.Retrofit.nextResponseBodyConverter(Retrofit.java:330)
        at retrofit2.Retrofit.responseBodyConverter(Retrofit.java:313)
        at retrofit2.ServiceMethod$Builder.createResponseConverter(ServiceMethod.java:739)
        	... 22 more
```

This type of error with moshi library seems common but only when used with proguard - which I did rule out.

I do see `Default tracker: 'foo123'` record in logs however.

Can someone assist with these issues?

Another question: I also see this [manual section](https://github.com/adjust/android_sdk#pre-installed-trackers) and I wonder - would adding that `config.setDefaultTracker("{TrackerToken}");` line and building apk with such code change do the same as re-packaging existing apk using adjust-dtt tool?

**Comment by uerceg** [comment]
Hi @Den-Rimus.

How did you manage to connect this crash with the fact that you have used `adjust-dtt` tool? I am trying to figure that out from the stack trace, but maybe I'm missing something obvious?

If you do see `Default tracker 'foo123'`, that's good - means that default tracker is properly set. In case you ran the tool, tool does nothing other than places certain config file inside of the APK from where our SDK tries to read it and if it does and everything in config file is written properly, we take default tracker value and assign it.

`setDefaultTracker` is a way to go when it comes to setting default tracker in case you are the one who owns the code and who is in power when it comes to APK generation. `adjust-dtt` tool was made because of the following use case: We were getting requests for default tracker to be set, but people who were supposed to perform this action didn't have any access to source code of apps, rather they just had APK files which they are supposed to distribute to various stores or whatever. So this tool intended to find a way for these people to simply run it and somehow automagically inject this config file for our SDK to pick it up and use default tracker value from it.

In case you have access to source code of the app and you are the one who is generating APK for distribution, I would say that you don't need to use `adjust-dtt` at all -> simply use `setDefaultTracker` method on `AdjustConfig` object when configuring SDK inside of your app and that's it.

**Comment by Den-Rimus** [comment]
> How did you manage to connect this crash with the fact that you have used `adjust-dtt` tool?
It works fine when I am not applying adjust-dtt on apk.

> In case you have access to source code of the app and you are the one who is generating APK for distribution, I would say that you don't need to use `adjust-dtt` at all
That's just what I needed to confirm, thanks!

Feel free to close this issue whenever you find expedient.
