### ISSUE TITLE
Android compatibility warning in playstore

### ISSUE THREAD

**Issue by rajiac2607** [adjust/android_sdk#441]
There are compatibility warnings in playstore like the below ,is there a fix for this in adjust?
`StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Ljava/net/Socket;->impl:Ljava/net/SocketImpl;
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredField(Native Method)
	at com.google.android.gms.org.conscrypt.Platform.getFileDescriptor(:com.google.android.gms@200914028@20.09.14 (100400-300565878):1)
	at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(:com.google.android.gms@200914028@20.09.14 (100400-300565878):6)
	at com.android.okhttp.okio.Okio$2.read(Okio.java:136)
	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
	at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
	at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
	at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
	at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:609)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:26)
	at com.google.firebase.perf.network.zzd.getResponseCode(com.google.firebase:firebase-perf@@19.0.5:81)
	at com.google.firebase.perf.network.zze.getResponseCode(com.google.firebase:firebase-perf@@19.0.5:15)
	at com.adjust.sdk.UtilNetworking.readHttpResponse(UtilNetworking.java:119)
	at com.adjust.sdk.UtilNetworking.createPOSTHttpsURLConnection(UtilNetworking.java:64)
	at com.adjust.sdk.RequestHandler.sendI(RequestHandler.java:88)
	at com.adjust.sdk.RequestHandler.access$000(RequestHandler.java:20)
	at com.adjust.sdk.RequestHandler$1.run(RequestHandler.java:47)
	at com.adjust.sdk.scheduler.SingleThreadCachedScheduler.tryExecuteRunnable(SingleThreadCachedScheduler.java:112)
	at com.adjust.sdk.scheduler.SingleThreadCachedScheduler.access$000(SingleThreadCachedScheduler.java:12)
	at com.adjust.sdk.scheduler.SingleThreadCachedScheduler$3.run(SingleThreadCachedScheduler.java:83)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)`

**Comment by uerceg** [comment]
Hi @rajiac2607 

And sorry for quite a delay in replying to this one. Are you still facing this issue with latest version of Adjust SDK?

Cheers

**Comment by uerceg** [comment]
In case this is still an issue for you and you have additional questions, feel free to comment/reopen. Cheers.
