### ISSUE TITLE
Fix IncorrectContextUse warning

### ISSUE THREAD

**Issue by eloev** [adjust/android_sdk#540]
When StrictMode is enabled, Android 11 or higher will display a warning if the app requests `WindowManager` on application contexts. 
When trying to send event
```
E/ContextImpl: Tried to access visual service WindowManager from a non-visual Context:com.myApp@82752ca 
Visual services, such as WindowManager, WallpaperService or LayoutInflater should be accessed from Activity
 or other visual Context. Use an Activity or a Context created with Context#createWindowContext(int, Bundle), 
which are adjusted to the configuration and visual bounds of an area on screen.
    java.lang.IllegalAccessException: Tried to access visual service WindowManager from a non-visual Context:com.myApp@82752ca
        at android.app.ContextImpl.getSystemService(ContextImpl.java:1926)
        at android.content.ContextWrapper.getSystemService(ContextWrapper.java:814)
        at com.adjust.sdk.sig.NativeLibHelper.nSign(Native Method)
        at com.adjust.sdk.sig.NativeLibHelper.sign(NativeLibHelper.java:15)
        at com.adjust.sdk.sig.SignerInstance.sign(SignerInstance.java:112)
        at com.adjust.sdk.sig.Signer.sign(Signer.java:74)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.adjust.sdk.Reflection.invokeMethod(Unknown Source:8)
        at com.adjust.sdk.Reflection.invokeInstanceMethod(Unknown Source:4)
        at com.adjust.sdk.AdjustSigner.sign(Unknown Source:46)
        at com.adjust.sdk.PackageBuilder.buildEventPackage(Unknown Source:36)
```
When tried to handle deeplink
```
E/ContextImpl: Tried to access visual service WindowManager from a non-visual Context:com.myApp@82752ca 
Visual services, such as WindowManager, WallpaperService or LayoutInflater should be accessed from Activity
 or other visual Context. Use an Activity or a Context created with Context#createWindowContext(int, Bundle), 
which are adjusted to the configuration and visual bounds of an area on screen.
    java.lang.IllegalAccessException: Tried to access visual service WindowManager from a non-visual Context:com.myApp@82752ca
        at android.app.ContextImpl.getSystemService(ContextImpl.java:1926)
        at android.content.ContextWrapper.getSystemService(ContextWrapper.java:814)
        at com.adjust.sdk.sig.NativeLibHelper.nSign(Native Method)
        at com.adjust.sdk.sig.NativeLibHelper.sign(NativeLibHelper.java:15)
        at com.adjust.sdk.sig.SignerInstance.sign(SignerInstance.java:112)
        at com.adjust.sdk.sig.Signer.sign(Signer.java:74)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.adjust.sdk.Reflection.invokeMethod(Unknown Source:8)
        at com.adjust.sdk.Reflection.invokeInstanceMethod(Unknown Source:4)
        at com.adjust.sdk.AdjustSigner.sign(Unknown Source:46)
        at com.adjust.sdk.PackageBuilder.buildClickPackage(Unknown Source:69)
        at com.adjust.sdk.PackageFactory.buildDeeplinkSdkClickPackage(Unknown Source:135)
```
Appcenter have the same bug in past, and this commit will help you 
https://github.com/facebook/facebook-android-sdk/commit/235a0a02692ac5a57d4c10b0bfb6477c9a003e99

**Comment by shashanksu** [comment]
Hi @eloev,
Thanks for reporting this.  To understand more on the issue, could you please confirm:
1. Which `context` being passed to the sdk during initialization?  I understand it's application context, but just to confirm.
2. Which Adjust SDK and Signature SDK version are you noticing this issue with?
Also, we aren't using `WindowManager` anywhere in our SDK, so the suggested fix (commit) doesn't appear to be relevant. 

Please share the asked details, so that we can look into this issue further, thanks.

**Comment by eloev** [comment]
Hi,
1) Yes, application context.
2) Adjust SDK version 4.33.2, updated to 4.33.3, problem still exists
Signature SDK version is 2.8.2 (in library name), in manifest android:versionCode="1", android:versionName="0.1.0". 
I contacted the manager for an update a week ago. I'll write here when I get the new Signature version and test it.

**Comment by shashanksu** [comment]
Thanks @eloev.  Can you also quickly confirm if the issue happens with or without Signature SDK?

**Comment by eloev** [comment]
Yes, everything is fine without the Signature SDK. 
After updating the version of the Signature SDK, I will write the results here

**Comment by eloev** [comment]
I solved this.
My old StrictMode configuraton:
```
            StrictMode.setVmPolicy(
                StrictMode.VmPolicy.Builder()
                    .detectAll()
                    .penaltyLog()
                    .build()
            )
```
            
Need disable StrictMode.VmPolicy.Builder.detectIncorrectContextUse()
Because func permitIncorrectContextUse() are hided, need write extension for StrictMode, which are copy of detectAll without incorrectContextUse()

**Comment by kibotu** [comment]
Thanks for the info. It's not critical at all. At this point it's just a slight inconvenience at most. 

Curious, so you already use a themed context wrapper? Which is valid with application context afaik.
