### ISSUE TITLE
StrictMode DiskReadViolation during initialization

### ISSUE THREAD

**Issue by mars885** [adjust/android_sdk#599]
Hey all.

We are using the `com.adjust.sdk:adjust-android:4.38.3` version of the SDK inside our app. During the initialization of the SDK with StrictMode enabled like so:

```kotlin
StrictMode.setThreadPolicy(
    StrictMode.ThreadPolicy.Builder()
        .detectDiskReads()
        .detectDiskWrites()
        .detectNetwork()
        .penaltyLog()
        .penaltyDeathOnNetwork()
        .build()
)
StrictMode.setVmPolicy(
    StrictMode.VmPolicy.Builder()
        .detectAll()
        .penaltyLog()
        .build()
)
```
we get the following reports:

1. 
```
14:21:57.545  D  StrictMode policy violation; ~duration=206 ms: android.os.strictmode.DiskReadViolation
                 	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1658)
                 	at libcore.io.BlockGuardOs.access(BlockGuardOs.java:74)
                 	at libcore.io.ForwardingOs.access(ForwardingOs.java:128)
                 	at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:7795)
                 	at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:313)
                 	at java.io.File.exists(File.java:813)
                 	at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:759)
                 	at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:750)
                 	at android.app.ContextImpl.getPreferencesDir(ContextImpl.java:706)
                 	at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java:931)
                 	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:553)
                 	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:217)
                 	at com.adjust.sdk.SharedPreferencesManager.<init>(Unknown Source:6)
                 	at com.adjust.sdk.SharedPreferencesManager.getDefaultInstance(Unknown Source:9)
                 	at com.adjust.sdk.AdjustInstance.setSendingReferrersAsNotSent(Unknown Source:0)
                 	at com.adjust.sdk.AdjustInstance.onCreate(Unknown Source:93)
                 	at com.adjust.sdk.Adjust.onCreate(Unknown Source:4)
                 	at *.AdjustAnalytics.init(AdjustAnalytics.kt:13)
                 	at *.AdjustInitializer.init(AdjustInitializer.kt:14)
                 	at *.CompositeInitializer.init(CompositeInitializer.kt:8)
                 	at *.App.onCreate(App.kt:16)
                 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1277)
                 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6805)
                 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2132)
                 	at android.os.Handler.dispatchMessage(Handler.java:106)
                 	at android.os.Looper.loopOnce(Looper.java:201)
                 	at android.os.Looper.loop(Looper.java:288)
                 	at android.app.ActivityThread.main(ActivityThread.java:7918)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

2.
```
14:21:57.550  D  StrictMode policy violation; ~duration=205 ms: android.os.strictmode.DiskReadViolation
                 	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1658)
                 	at android.app.SharedPreferencesImpl.awaitLoadedLocked(SharedPreferencesImpl.java:275)
                 	at android.app.SharedPreferencesImpl.edit(SharedPreferencesImpl.java:368)
                 	at com.adjust.sdk.SharedPreferencesManager.<init>(Unknown Source:12)
                 	at com.adjust.sdk.SharedPreferencesManager.getDefaultInstance(Unknown Source:9)
                 	at com.adjust.sdk.AdjustInstance.setSendingReferrersAsNotSent(Unknown Source:0)
                 	at com.adjust.sdk.AdjustInstance.onCreate(Unknown Source:93)
                 	at com.adjust.sdk.Adjust.onCreate(Unknown Source:4)
                 	at *.AdjustAnalytics.init(AdjustAnalytics.kt:13)
                 	at *.AdjustInitializer.init(AdjustInitializer.kt:14)
                 	at *.CompositeInitializer.init(CompositeInitializer.kt:8)
                 	at *.App.onCreate(App.kt:16)
                 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1277)
                 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6805)
                 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2132)
                 	at android.os.Handler.dispatchMessage(Handler.java:106)
                 	at android.os.Looper.loopOnce(Looper.java:201)
                 	at android.os.Looper.loop(Looper.java:288)
                 	at android.app.ActivityThread.main(ActivityThread.java:7918)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

We've followed the setup instructions from [here](https://help.adjust.com/en/article/get-started-android-sdk#integrate-the-sdk) and basically have initialized the SDK from the `Application` class.

It almost takes half a second to initialize the SDK on the UI thread, which is quite a lot.

Can something be done about this in terms of a fix? Should we initialize it on the backgrround thread and will it even work?

Looking forward to hearing from you.

**Comment by oalpayli** [comment]
we get too. Still waiting response about it.

**Comment by uerceg** [comment]
Hey guys,

Sorry for a bit of delay on this one. This is being checked on our side. We'll keep you posted on the progress.

**Comment by uerceg** [comment]
Hey guys,

We have just shipped v5.0.1 patch update where this issue should hopefully be addressed. Please, give it a shot and looking forward to hearing back from you if the issue has been resolved (or not).

Cheers

**Comment by mars885** [comment]
Hey.

We've updated to the 5.0.1 and can confirm that those reports are now gone.

Thanks.

**Comment by uerceg** [comment]
Thank you very much for the confirmation. I will close the issue, but in case anyone else still faces this problem post 5.0.1, feel free to comment / reopen.
